"""add previous_order_status

Revision ID: 040e80d39686
Revises: 1ab03f2dbb5c
Create Date: 2024-02-01 04:11:53.745879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '040e80d39686'
down_revision: Union[str, None] = '1ab03f2dbb5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_status_previous', sa.String(), nullable=True))
    op.drop_column('orders', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.drop_column('orders', 'order_status_previous')
    # ### end Alembic commands ###
