"""add destination_warehouse_id to orders

Revision ID: 1ab03f2dbb5c
Revises: 03229992eb36
Create Date: 2024-02-01 03:52:06.886695

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1ab03f2dbb5c'
down_revision: Union[str, None] = '03229992eb36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('destination_warehouse_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'warehouses', ['destination_warehouse_id'], ['id'])
    op.alter_column(
        'shipping',
        'status',
        existing_type=postgresql.ENUM(
            'FINISHED',
            'IN_TRANSIT',
            'CANCELED',
            'NEW',
            'WAITING_DRIVER',
            name='shippingstatus'),
        nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'shipping',
        'status',
        existing_type=postgresql.ENUM(
            'FINISHED',
            'IN_TRANSIT',
            'CANCELED',
            'NEW',
            'WAITING_DRIVER',
            name='shippingstatus'),
        nullable=True)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'destination_warehouse_id')
    # ### end Alembic commands ###
