"""set nullable fields

Revision ID: 2d6547a6a381
Revises: efac2cc5301d
Create Date: 2024-02-16 14:29:50.346894

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2d6547a6a381'
down_revision: Union[str, None] = 'efac2cc5301d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipping', 'address',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('shipping', 'cargo_weight',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=True)
    op.alter_column('shipping', 'cargo_volume',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipping', 'cargo_volume',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=False)
    op.alter_column('shipping', 'cargo_weight',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=False)
    op.alter_column('shipping', 'address',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###
