"""make many to many

Revision ID: 2e7eb6cc059c
Revises: 220bb53c8e6e
Create Date: 2024-01-25 01:47:13.735208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e7eb6cc059c'
down_revision: Union[str, None] = '220bb53c8e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_driver_association',
    sa.Column('shipping_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipping_id'], ['shipping.id'], )
    )
    op.drop_constraint('shipping_driver_id_fkey', 'shipping', type_='foreignkey')
    op.drop_column('shipping', 'driver_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping', sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('shipping_driver_id_fkey', 'shipping', 'users', ['driver_id'], ['id'])
    op.drop_table('shipping_driver_association')
    # ### end Alembic commands ###
