"""change to warehouses action code

Revision ID: 2eb57c37803b
Revises: 2d6547a6a381
Create Date: 2024-02-25 11:27:21.496778

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2eb57c37803b'
down_revision: Union[str, None] = '2d6547a6a381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('action_history_warehouse_id_fkey', 'action_history', type_='foreignkey')
    op.create_foreign_key(None, 'action_history', 'warehouses', ['warehouse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'action_history', type_='foreignkey')
    op.create_foreign_key('action_history_warehouse_id_fkey', 'action_history', 'users', ['warehouse_id'], ['id'])
    # ### end Alembic commands ###
