"""remove CheckConstraint

Revision ID: 30667226b816
Revises: 1b04ca3d7cc1
Create Date: 2024-04-21 19:52:37.966514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30667226b816'
down_revision: Union[str, None] = '1b04ca3d7cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE tarifs
        DROP CONSTRAINT check_amount_max_100
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE tarifs
        ADD CONSTRAINT check_amount_max_100 CHECK (amount <= 100)
        """
    )
    # ### end Alembic commands ###
