"""add relationship

Revision ID: 3e55f0d8d87f
Revises: 466ad4589201
Create Date: 2024-02-07 19:38:36.724316

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '3e55f0d8d87f'
down_revision: Union[str, None] = '466ad4589201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
