"""make nullable fields order

Revision ID: 40c77f4cf21b
Revises: d289b2aa5748
Create Date: 2024-03-19 17:23:58.468117

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '40c77f4cf21b'
down_revision: Union[str, None] = 'd289b2aa5748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'total_weight',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=True)
    op.alter_column('orders', 'total_volume',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'total_volume',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=False)
    op.alter_column('orders', 'total_weight',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=False)
    # ### end Alembic commands ###
