"""add is_active to orders

Revision ID: 4356f6ee170d
Revises: f48f0a560360
Create Date: 2024-01-31 11:24:11.624865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4356f6ee170d'
down_revision: Union[str, None] = 'f48f0a560360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_active')
    # ### end Alembic commands ###
