"""add constraint

Revision ID: 43de23afed5e
Revises: 04e40cd94848
Create Date: 2024-03-15 20:07:36.292819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43de23afed5e'
down_revision: Union[str, None] = '04e40cd94848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE tarifs
        ADD CONSTRAINT check_amount_max_100 CHECK (amount <= 100)
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE tarifs
        DROP CONSTRAINT check_amount_max_100
        """
    )
    # ### end Alembic commands ###
