"""remove is_responded from Shipping

Revision ID: 466ad4589201
Revises: a366e2ca76ba
Create Date: 2024-02-06 19:09:33.922723

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '466ad4589201'
down_revision: Union[str, None] = 'a366e2ca76ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    ...
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('shipping', 'is_responded')
    ### end Alembic commands ###


def downgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('shipping', sa.Column('is_responded', sa.BOOLEAN(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
    ...
