"""Groups and permissions m2m relation

Revision ID: 46a82b53e856
Revises: 83718e4678b6
Create Date: 2024-03-07 02:25:30.076833

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '46a82b53e856'
down_revision: Union[str, None] = '83718e4678b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fastapi_auth_permission_group_id_fkey', 'fastapi_auth_permission', type_='foreignkey')
    op.drop_column('fastapi_auth_permission', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fastapi_auth_permission', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(
        'fastapi_auth_permission_group_id_fkey',
        'fastapi_auth_permission',
        'fastapi_auth_group',
        ['group_id'],
        ['id'])
    # ### end Alembic commands ###
