"""add order_items, rm status

Revision ID: 5312783180db
Revises: f48f0a560360
Create Date: 2024-01-30 10:13:23.600262

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5312783180db'
down_revision: Union[str, None] = 'f48f0a560360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_order_items',
                    sa.Column('shipping_id', sa.Integer(), nullable=True),
                    sa.Column('order_item_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
                    sa.ForeignKeyConstraint(['shipping_id'], ['shipping.id'], )
                    )
    op.drop_column('shipping', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'shipping',
        sa.Column(
            'status',
            postgresql.ENUM(
                'FINISHED',
                'IN_TRANSIT',
                'CANCELED',
                'NEW',
                'WAITING_DRIVER',
                name='shippingstatus'),
            autoincrement=False,
            nullable=False))
    op.drop_table('shipping_order_items')
    # ### end Alembic commands ###
