"""add comment to payment

Revision ID: 611638a18987
Revises: c782bcd277fd
Create Date: 2024-03-12 01:27:22.608693

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '611638a18987'
down_revision: Union[str, None] = 'c782bcd277fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'comment')
    # ### end Alembic commands ###
