"""make unique constraint on combination of direction fields

Revision ID: 6af973079260
Revises: eac1c8bbe1ea
Create Date: 2024-02-26 00:28:12.042909

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6af973079260'
down_revision: Union[str, None] = 'eac1c8bbe1ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('directions_arrival_city_id_key', 'directions', type_='unique')
    op.drop_constraint('directions_departure_city_id_key', 'directions', type_='unique')
    op.drop_constraint('directions_transportation_type_key', 'directions', type_='unique')
    op.create_unique_constraint('uq_transportation_type_arrival_departure_city', 'directions', [
                                'arrival_city_id', 'departure_city_id', 'transportation_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transportation_type_arrival_departure_city', 'directions', type_='unique')
    op.create_unique_constraint('directions_transportation_type_key', 'directions', ['transportation_type'])
    op.create_unique_constraint('directions_departure_city_id_key', 'directions', ['departure_city_id'])
    op.create_unique_constraint('directions_arrival_city_id_key', 'directions', ['arrival_city_id'])
    # ### end Alembic commands ###
