"""make order item unique

Revision ID: 6de1b66f5829
Revises: b8d3d94a338e
Create Date: 2024-01-26 19:39:56.311494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de1b66f5829'
down_revision: Union[str, None] = 'b8d3d94a338e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'order_items', ['qr_code_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='unique')
    # ### end Alembic commands ###
