"""add fields for user model for CourierStatistics

Revision ID: 71583b6c8030
Revises: 2e4e72045806
Create Date: 2024-03-27 01:19:56.405058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71583b6c8030'
down_revision: Union[str, None] = '2e4e72045806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('selected_orders', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('users', sa.Column('total_profit', sa.Float(), nullable=True, server_default='0'))
    op.add_column('users', sa.Column('delivered_orders', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'delivered_orders')
    op.drop_column('users', 'total_profit')
    op.drop_column('users', 'selected_orders')
    # ### end Alembic commands ###
