"""change direction_id to nullable=True in Tarifs

Revision ID: 7cabd012a01f
Revises: db1692492005
Create Date: 2024-04-04 02:17:35.152564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cabd012a01f'
down_revision: Union[str, None] = 'db1692492005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tarifs', 'direction_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tarifs', 'direction_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
