"""add order_item_id to action history

Revision ID: 84089921d98d
Revises: 6de1b66f5829
Create Date: 2024-01-28 01:27:40.867088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84089921d98d'
down_revision: Union[str, None] = '6de1b66f5829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_history', sa.Column('order_item_id', sa.Integer(), nullable=True))
    op.drop_constraint('action_history_order_id_fkey', 'action_history', type_='foreignkey')
    op.create_foreign_key(None, 'action_history', 'order_items', ['order_item_id'], ['id'])
    op.drop_column('action_history', 'order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_history', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'action_history', type_='foreignkey')
    op.create_foreign_key('action_history_order_id_fkey', 'action_history', 'orders', ['order_id'], ['id'])
    op.drop_column('action_history', 'order_item_id')
    # ### end Alembic commands ###
