"""add days shipping and new status to respond

Revision ID: 8451db9ef4b8
Revises: 296004a91f30
Create Date: 2024-02-01 15:58:34.153439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8451db9ef4b8'
down_revision: Union[str, None] = '296004a91f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping', sa.Column('days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipping', 'days')
    # ### end Alembic commands ###
