"""add manager_id

Revision ID: 8a68d1bc9679
Revises: f66b9da9a5fb
Create Date: 2024-01-25 02:39:30.073001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a68d1bc9679'
down_revision: Union[str, None] = 'f66b9da9a5fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_history', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'action_history', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'action_history', type_='foreignkey')
    op.drop_column('action_history', 'manager_id')
    # ### end Alembic commands ###
