"""add rating to user

Revision ID: 9496345ad75d
Revises: 6f3f8a0a10e1
Create Date: 2024-01-31 10:43:19.604235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9496345ad75d'
down_revision: Union[str, None] = '6f3f8a0a10e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rating')
    # ### end Alembic commands ###
