"""add new field orders to Shpping model

Revision ID: 97d3326fa055
Revises: 3e55f0d8d87f
Create Date: 2024-02-07 19:52:48.690805

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '97d3326fa055'
down_revision: Union[str, None] = '3e55f0d8d87f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_order',
                    sa.Column('shipping_id', sa.Integer(), nullable=True),
                    sa.Column('order_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
                    sa.ForeignKeyConstraint(['shipping_id'], ['shipping.id'], )
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipping_order')
    # ### end Alembic commands ###
