"""fix relationship

Revision ID: 9b57186e4f52
Revises: 97d3326fa055
Create Date: 2024-02-07 20:14:28.396220

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '9b57186e4f52'
down_revision: Union[str, None] = '97d3326fa055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
