"""add reasons

Revision ID: a366e2ca76ba
Revises: cb0d071d7602
Create Date: 2024-02-05 00:39:30.701386

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a366e2ca76ba'
down_revision: Union[str, None] = 'cb0d071d7602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'orders',
        sa.Column(
            'not_delivered_reason',
            sa.String(),
            nullable=True))
    op.add_column(
        'orders',
        sa.Column(
            'cancellation_reason',
            sa.String(),
            nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'cancellation_reason')
    op.drop_column('orders', 'not_delivered_reason')
    # ### end Alembic commands ###
