"""add order_id

Revision ID: a884e3fe60a3
Revises: b38f74241dfe
Create Date: 2024-02-11 21:53:25.370560

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a884e3fe60a3'
down_revision: Union[str, None] = 'b38f74241dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_history', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'action_history', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'action_history', type_='foreignkey')
    op.drop_column('action_history', 'order_id')
    # ### end Alembic commands ###
