"""make nullable fields payment

Revision ID: ae012a494022
Revises: 40c77f4cf21b
Create Date: 2024-03-19 20:01:30.848090

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ae012a494022'
down_revision: Union[str, None] = '40c77f4cf21b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'payment_type',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('payments', 'payer_type',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'payer_type',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('payments', 'payment_type',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###
