"""shipping_warehouse

Revision ID: b178f237cf1b
Revises: 1b66b7e9e9c5
Create Date: 2024-04-08 20:48:46.500299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b178f237cf1b'
down_revision: Union[str, None] = '1b66b7e9e9c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping_warehouse', sa.Column('is_visited', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.alter_column('shipping_warehouse', 'shipping_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('shipping_warehouse', 'warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipping_warehouse', 'warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('shipping_warehouse', 'shipping_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('shipping_warehouse', 'is_loaded')
    # ### end Alembic commands ###
