"""add lazy to order_items

Revision ID: b7dc3e9b1f94
Revises: c8ec4fa54ff8
Create Date: 2024-01-31 03:47:35.205638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7dc3e9b1f94'
down_revision: Union[str, None] = 'c8ec4fa54ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
