"""add driver contract

Revision ID: b8d3d94a338e
Revises: 8a68d1bc9679
Create Date: 2024-01-26 13:16:26.470273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d3d94a338e'
down_revision: Union[str, None] = '8a68d1bc9679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_driver_contract_accepted')
    op.add_column('otp_signing_code', sa.Column('otp_type', sa.String(length=100), nullable=True, comment='otp type'))
    op.add_column('shipping', sa.Column('is_driver_contract_accepted', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipping', 'is_driver_contract_accepted')
    op.drop_column('otp_signing_code', 'otp_type')
    op.add_column('orders', sa.Column('is_driver_contract_accepted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
