"""make order public

Revision ID: bd246bca9ba1
Revises: 6af973079260
Create Date: 2024-02-29 09:12:17.798765

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bd246bca9ba1'
down_revision: Union[str, None] = '6af973079260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'creator',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'creator',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###
