"""add direction and warehouses to shipping

Revision ID: c1faa055cfd6
Revises: 9a23136e6508
Create Date: 2024-01-29 02:54:52.892447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1faa055cfd6'
down_revision: Union[str, None] = '9a23136e6508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_warehouse',
    sa.Column('shipping_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shipping_id'], ['shipping.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], )
    )
    op.add_column('shipping', sa.Column('direction_id', sa.Integer(), nullable=True))
    op.drop_constraint('shipping_arrival_city_id_fkey', 'shipping', type_='foreignkey')
    op.drop_constraint('shipping_departure_city_id_fkey', 'shipping', type_='foreignkey')
    op.create_foreign_key(None, 'shipping', 'directions', ['direction_id'], ['id'])
    op.drop_column('shipping', 'departure_city_id')
    op.drop_column('shipping', 'arrival_city_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping', sa.Column('arrival_city_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shipping', sa.Column('departure_city_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shipping', type_='foreignkey')
    op.create_foreign_key('shipping_departure_city_id_fkey', 'shipping', 'cities', ['departure_city_id'], ['id'])
    op.create_foreign_key('shipping_arrival_city_id_fkey', 'shipping', 'cities', ['arrival_city_id'], ['id'])
    op.drop_column('shipping', 'direction_id')
    op.drop_table('shipping_warehouse')
    # ### end Alembic commands ###
