"""add new field waiver_agreement_url

Revision ID: c782bcd277fd
Revises: 46a82b53e856
Create Date: 2024-03-09 20:58:41.522313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c782bcd277fd'
down_revision: Union[str, None] = '46a82b53e856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('waiver_agreement_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'waiver_agreement_url')
    # ### end Alembic commands ###
