"""add status in Shipping

Revision ID: c8ec4fa54ff8
Revises: 5312783180db
Create Date: 2024-01-30 10:15:06.681329

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c8ec4fa54ff8'
down_revision: Union[str, None] = '5312783180db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'shipping',
        sa.Column(
            'status',
            postgresql.ENUM(
                'FINISHED',
                'IN_TRANSIT',
                'CANCELED',
                'NEW',
                'WAITING_DRIVER',
                'CANCELED',
                name='shippingstatus'),
            nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipping', 'status')
    # ### end Alembic commands ###
