"""add lat,long

Revision ID: cb0d071d7602
Revises: 8451db9ef4b8
Create Date: 2024-02-02 11:00:09.457892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0d071d7602'
down_revision: Union[str, None] = '8451db9ef4b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('shipping', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipping', 'longitude')
    op.drop_column('shipping', 'latitude')
    # ### end Alembic commands ###
