"""add delivery type

Revision ID: cb536e4a86ea
Revises: 45937ecf0df8
Create Date: 2024-01-23 12:19:49.530268

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cb536e4a86ea'
down_revision: Union[str, None] = '45937ecf0df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_type', sa.String(), server_default='DELIVERY', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_type')
    # ### end Alembic commands ###
