"""make nullable fields order

Revision ID: d289b2aa5748
Revises: b9270f78c2a5
Create Date: 2024-03-19 17:21:43.832090

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd289b2aa5748'
down_revision: Union[str, None] = 'b9270f78c2a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'delivery_type',
                    existing_type=sa.VARCHAR(),
                    nullable=True,
                    existing_server_default=sa.text("'DELIVERY'::character varying"))
    op.alter_column('orders', 'cargo_pickup_type',
                    existing_type=postgresql.ENUM('DELIVERY', 'PICKUP', name='deliverytype'),
                    nullable=True,
                    existing_server_default=sa.text("'PICKUP'::deliverytype"))
    op.alter_column('orders', 'insurance',
                    existing_type=sa.NUMERIC(precision=10, scale=2),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'insurance',
                    existing_type=sa.NUMERIC(precision=10, scale=2),
                    nullable=False)
    op.alter_column('orders', 'cargo_pickup_type',
                    existing_type=postgresql.ENUM('DELIVERY', 'PICKUP', name='deliverytype'),
                    nullable=False,
                    existing_server_default=sa.text("'PICKUP'::deliverytype"))
    op.alter_column('orders', 'delivery_type',
                    existing_type=sa.VARCHAR(),
                    nullable=False,
                    existing_server_default=sa.text("'DELIVERY'::character varying"))
    # ### end Alembic commands ###
