"""change shipping

Revision ID: d5b3a2c3581d
Revises: a884e3fe60a3
Create Date: 2024-02-19 12:35:54.483032

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd5b3a2c3581d'
down_revision: Union[str, None] = 'a884e3fe60a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping', sa.Column('start_warehouse_id', sa.Integer(), nullable=True))
    op.add_column('shipping', sa.Column('end_warehouse_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shipping', 'warehouses', ['start_warehouse_id'], ['id'])
    op.create_foreign_key(None, 'shipping', 'warehouses', ['end_warehouse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipping', type_='foreignkey')
    op.drop_constraint(None, 'shipping', type_='foreignkey')
    op.drop_column('shipping', 'end_warehouse_id')
    op.drop_column('shipping', 'start_warehouse_id')
    # ### end Alembic commands ###
