"""add phone field for warehouses

Revision ID: d64bf7575a87
Revises: c782bcd277fd
Create Date: 2024-03-12 02:01:43.950446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd64bf7575a87'
down_revision: Union[str, None] = 'c782bcd277fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouses', 'phone')
    # ### end Alembic commands ###
