"""add new field for order

Revision ID: d781aab01736
Revises: d64bf7575a87
Create Date: 2024-03-17 00:37:49.284348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd781aab01736'
down_revision: Union[str, None] = 'd64bf7575a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('expenses_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'expenses_price')
    # ### end Alembic commands ###
