"""add relation with user and direction

Revision ID: d87234808f5c
Revises: 28ceda714f21
Create Date: 2024-02-23 17:54:10.989290

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd87234808f5c'
down_revision: Union[str, None] = '28ceda714f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'shipping',
        'status',
        existing_type=postgresql.ENUM(
            'FINISHED',
            'IN_TRANSIT',
            'CANCELED',
            'NEW',
            'WAITING_DRIVER',
            name='shippingstatus'),
        nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'shipping',
        'status',
        existing_type=postgresql.ENUM(
            'FINISHED',
            'IN_TRANSIT',
            'CANCELED',
            'NEW',
            'WAITING_DRIVER',
            name='shippingstatus'),
        nullable=True)
    # ### end Alembic commands ###
