"""add quantity_of_order_items

Revision ID: dab06b67a4e9
Revises: 9b57186e4f52
Create Date: 2024-02-07 21:26:03.418794

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dab06b67a4e9'
down_revision: Union[str, None] = '9b57186e4f52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'orders',
        sa.Column(
            'quantity_of_order_items',
            sa.Integer(),
            nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'quantity_of_order_items')
    # ### end Alembic commands ###
