"""add receiver_address

Revision ID: dae87cf5cfd3
Revises: 09e17ebb27dc
Create Date: 2024-02-02 00:51:10.005232

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dae87cf5cfd3'
down_revision: Union[str, None] = '09e17ebb27dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'address',
                    new_column_name='sender_address', type_=sa.String(), nullable=False)
    op.add_column('orders', sa.Column('receiver_address', sa.String(), nullable=False, server_default='Толстой, 1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'sender_address',
                    new_column_name='address', type_=sa.String(), nullable=False)
    op.drop_column('orders', 'receiver_address')
    # ### end Alembic commands ###

