"""add name_ru to Group

Revision ID: db1692492005
Revises: 08b041238e00
Create Date: 2024-03-18 00:06:07.878242

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'db1692492005'
down_revision: Union[str, None] = '08b041238e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'fastapi_auth_group',
        sa.Column(
            'name_ru',
            sa.String(
                length=150),
            nullable=True,
            comment='group name in English',
            default='user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fastapi_auth_group', 'name_ru')
    # ### end Alembic commands ###
