"""add transportation type

Revision ID: efac2cc5301d
Revises: 696b8edf851b
Create Date: 2024-02-09 02:33:23.799025

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'efac2cc5301d'
down_revision: Union[str, None] = '696b8edf851b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transportation_types',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_transportation_types_id'), 'transportation_types', ['id'], unique=False)
    op.create_index(op.f('ix_transportation_types_name'), 'transportation_types', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transportation_types_name'), table_name='transportation_types')
    op.drop_index(op.f('ix_transportation_types_id'), table_name='transportation_types')
    op.drop_table('transportation_types')
    # ### end Alembic commands ###
