"""add direction, warehouse to Order

Revision ID: f48f0a560360
Revises: 766d87b5eb70
Create Date: 2024-01-29 16:22:27.630618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f48f0a560360'
down_revision: Union[str, None] = '766d87b5eb70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('direction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'directions', ['direction_id'], ['id'])
    op.create_foreign_key(None, 'users', 'warehouses', ['warehouse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'direction_id')
    op.drop_column('users', 'warehouse_id')
    # ### end Alembic commands ###
