"""add action history

Revision ID: f66b9da9a5fb
Revises: 220bb53c8e6e
Create Date: 2024-01-25 01:25:35.385728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f66b9da9a5fb'
down_revision: Union[str, None] = '220bb53c8e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('previous_action', sa.Integer(), nullable=True),
    sa.Column('action_description', sa.String(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_manager_id', sa.Integer(), nullable=True),
    sa.Column('arrival_city_id', sa.Integer(), nullable=True),
    sa.Column('departure_city_id', sa.Integer(), nullable=True),
    sa.Column('action_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['arrival_city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['courier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['departure_city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['previous_action'], ['action_history.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_history_id'), 'action_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_history_id'), table_name='action_history')
    op.drop_table('action_history')
    # ### end Alembic commands ###
