"""add two fields

Revision ID: fc8da9b79ffd
Revises: d87234808f5c
Create Date: 2024-02-25 17:03:43.517449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc8da9b79ffd'
down_revision: Union[str, None] = 'd87234808f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directions', sa.Column('email', sa.String(), nullable=False))
    op.add_column('directions', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('directions', 'password')
    op.drop_column('directions', 'email')
    # ### end Alembic commands ###
